In [1]:
import numpy as np
import pandas as pd

# PART A: NUMPY ARRAY OPERATIONS - Temperature Analysis

print("========== PART A: NUMPY ==========")

# 1. Create 1D NumPy Array
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print("\n1. Week 1 Temperatures Array:")
print(temperatures_w1)


========== PART A: NUMPY ==========

1. Week 1 Temperatures Array:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [2]:
# 2. Inspection and Properties
print("\n2. Inspection:")
print(f"Shape: {temperatures_w1.shape}")
print(f"Data Type (dtype): {temperatures_w1.dtype}")
print(f"Number of elements (size): {temperatures_w1.size}")
print(f"Dimensions (ndim): {temperatures_w1.ndim}")


2. Inspection:
Shape: (7,)
Data Type (dtype): float64
Number of elements (size): 7
Dimensions (ndim): 1


In [3]:
# 3. Array Operations
# Celsius to Fahrenheit
temperatures_f = (temperatures_w1 * 9/5) + 32
print("\n3. Array Operations:")
print(f"Temperatures in Fahrenheit: {temperatures_f}")
print(f"Max Temp (C): {np.max(temperatures_w1)}")
print(f"Min Temp (C): {np.min(temperatures_w1)}")
print(f"Mean Temp (C): {np.mean(temperatures_w1):.2f}")
print(f"Mean Temp (F): {np.mean(temperatures_f):.2f}")



3. Array Operations:
Temperatures in Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Max Temp (C): 26.1
Min Temp (C): 20.8
Mean Temp (C): 23.54
Mean Temp (F): 74.38


In [4]:
# 4. Array Slicing and Indexing
print("\n4. Slicing & Indexing:")
print(f"First three days: {temperatures_w1[0:3]}") # or [:3]
print(f"Weekend (last two days): {temperatures_w1[-2:]}")
print(f"Middle three days (Tue-Thu): {temperatures_w1[2:5]}") # index 2,3,4


4. Slicing & Indexing:
First three days: [22.5 25.3 20.8]
Weekend (last two days): [24.8 21.9]
Middle three days (Tue-Thu): [20.8 23.4 26.1]


In [5]:
# 5. Create a 2D Array
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9], # Week 1
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] # Week 2
])
print("\n5. 2D Array (2 Weeks):")
print(temperatures)


5. 2D Array (2 Weeks):
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [6]:
# 6. Inspect and Slice the 2D Array
print("\n6. 2D Array Inspection & Slicing:")
print(f"Shape: {temperatures.shape} -> 2 rows (weeks), 7 cols (days)")
print(f"Dtype: {temperatures.dtype}")
print(f"Total elements: {temperatures.size}")
print(f"Week 1: {temperatures[0]}")
print(f"Week 2: {temperatures[1]}")
print(f"Weekends for both weeks (last 2 days): \n{temperatures[:, -2:]}")
print(f"Week 1 Weekend: {temperatures[0, -2:]}")
print(f"Week 2 Weekend: {temperatures[1, -2:]}")



6. 2D Array Inspection & Slicing:
Shape: (2, 7) -> 2 rows (weeks), 7 cols (days)
Dtype: float64
Total elements: 14
Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Weekends for both weeks (last 2 days): 
[[24.8 21.9]
 [22.8 20.1]]
Week 1 Weekend: [24.8 21.9]
Week 2 Weekend: [22.8 20.1]


In [7]:
# PART B: PANDAS SERIES

print("\n\n========== PART B: PANDAS SERIES ==========")

# 1. Creating Pandas Series
marks = pd.Series([95, 92, 89, 85, 80], index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'], name='Marks')
print("\n1. Series 'marks':")
print(marks)




========== PART B: PANDAS SERIES ==========

1. Series 'marks':
Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
Name: Marks, dtype: int64


In [8]:
# 2. Indexing and Slicing
print("\n2. Indexing & Slicing:")
print(f"1st rank student mark (integer position [0]): {marks.iloc[0]}")
# Using integer index position
print(f"1st rank mark using [0]: {marks[0]}")

print(f"\nTop 3 ranks using loc:\n{marks.loc['Rank1':'Rank3']}")
print(f"\n3rd-ranked student using iloc[2]: {marks.iloc[2]}")
print(f"\nMarks > 90 (Boolean Mask):\n{marks[marks > 90]}")



2. Indexing & Slicing:
1st rank student mark (integer position [0]): 95
1st rank mark using [0]: 95

Top 3 ranks using loc:
Rank1    95
Rank2    92
Rank3    89
Name: Marks, dtype: int64

3rd-ranked student using iloc[2]: 89

Marks > 90 (Boolean Mask):
Rank1    95
Rank2    92
Name: Marks, dtype: int64


/tmp/ipykernel_1898/3182463056.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"1st rank mark using [0]: {marks[0]}")


In [9]:
# 3. Manipulating Series
print("\n3. Manipulating Series:")
marks['Rank1'] = 100
print(f"After modifying Rank1 to 100:\n{marks}")

marks = marks.drop('Rank5')
print(f"\nAfter removing last rank (Rank5):\n{marks}")

cgpa = marks / 10
print(f"\nCGPA (Marks/10):\n{cgpa}")



3. Manipulating Series:
After modifying Rank1 to 100:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
Name: Marks, dtype: int64

After removing last rank (Rank5):
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Name: Marks, dtype: int64

CGPA (Marks/10):
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
Name: Marks, dtype: float64


In [10]:
# PART C: PANDAS DATAFRAME

print("\n\n========== PART C: PANDAS DATAFRAME ==========")

# 1. Creating DataFrame
data = {
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
}
transactions = pd.DataFrame(data)
print("\n1. Transactions DataFrame:")
print(transactions)




========== PART C: PANDAS DATAFRAME ==========

1. Transactions DataFrame:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [11]:
# 2. Data Exploration
print("\n2. Data Exploration:")
print("\nHead (first 5):")
print(transactions.head())
print("\nTail (last 5):")
print(transactions.tail())
print(f"\nShape: {transactions.shape}")
print(f"Column Names: {list(transactions.columns)}")
print(f"Data Types:\n{transactions.dtypes}")
print(f"\nInfo:")
print(transactions.info())

print("\nOnly ProductCategory and Amount columns:")
print(transactions[['ProductCategory', 'Amount']])

print("\nLast 3 columns using iloc:")
print(transactions.iloc[:, -3:]) # last 3 cols = ProductCategory, Region, Amount

print("\nFilter: Region='North' and Amount>200:")
filtered = transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]
print(filtered)

print("\nValue counts for ProductCategory:")
print(transactions['ProductCategory'].value_counts())

print("\nUnique values in Region:")
print(transactions['Region'].unique())

print("\nGroup by Region and mean Amount:")
print(transactions.groupby('Region')['Amount'].mean())



2. Data Exploration:

Head (first 5):
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Tail (last 5):
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Shape: (10, 4)
Column Names: ['TransactionID', 'ProductCategory', 'Region', 'Amount']
Data Types:
TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype 

In [12]:
# 3. Manipulating the DataFrame
print("\n3. Manipulating DataFrame:")

# Modify Amount for TransactionID 102 to 165
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
print("\nAfter modifying TransactionID 102 Amount to 165:")
print(transactions)

# Add new column Discount (10% of Amount)
transactions['Discount'] = transactions['Amount'] * 0.10
print("\nAfter adding Discount column (10%):")
print(transactions)

# Remove row with TransactionID 109
transactions = transactions[transactions['TransactionID']!= 109]
print("\nAfter removing TransactionID 109:")
print(transactions)

# Delete Discount column
transactions = transactions.drop(columns=['Discount'])
print("\nAfter deleting Discount column (Final DataFrame):")
print(transactions)


3. Manipulating DataFrame:

After modifying TransactionID 102 Amount to 165:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

After adding Discount column (10%):
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5        